# Generated by Django 4.2.2 on 2023-06-19 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speaker",
            name="conferences",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.DeleteModel(
            name="Speaker",
        ),
    ]
